version: '3.8'

services:
  
  vote:
    build: ./vote
    container_name: vote
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - zebra-unicorn-network

  result:
    build: ./result
    container_name: result
    ports:
      - "8081:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - zebra-unicorn-network

  worker:
    build: ./worker
    container_name: worker
    ports:
      - "8082:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - zebra-unicorn-network
  
  redis:
    image: redis:3.2
    container_name: redis
    volumes:
      - type: volume
        source: redis-data
        target: /data
    networks:
      - zebra-unicorn-network

  postgres:
    image: postgres:9.4
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    networks:
      - zebra-unicorn-network
    
volumes:
  redis-data:
    name: zebra-unicorn-redis-data
  db-data:
    name: zebra-unicorn-db-data

networks:
  zebra-unicorn-network:
    name: zebra-unicorn-network