version: '3.8'

services:
  vote:
    build: ./vote
    container_name: vote
    ports:
      - "8080:8080"

  redis:
    image: redis:3.2
    container_name: redis

  result:
    build: ./result
    container_name: result
    ports:
      - "8081:8080"