server.servlet.context-path: "/api"

spring:
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: create
  redis:
    database: '0'
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}



  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
